 - name: Kernel Configure
      run: |
        ./build config               
                os_patch_level=2020-12
                model=G975F          
                name="OwnKernel"       
                +magisk+canary       
                +wireguard           
                +nohardening         
                +1000hz


