 - name: Kernel Configure
      run: |
        ./build config               
                os_patch_level=2023-01
                model=G970F          
                name="OwnKernel"       
                +magisk+canary       
                +wireguard           
                +nohardening         
                +1000hz


