- name: Kernel Configure
      run: |
        ./build config         
                model=G970F    
                name="CRUEL-V3.3"
                +magisk        
                +nohardening   
                +ttl           
                +wireguard     
                +cifs          
                +sdfat         
                +ntfs          
                +tcp_cibuc     
                +morosound     
                +boeffla_wl_blocker
